{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-11-12T22:49:40.521886Z",
     "start_time": "2020-11-12T22:49:40.516073Z"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "env: CUDA_DEVICE_ORDER=PCI_BUS_ID\n",
      "env: CUDA_VISIBLE_DEVICES=1\n"
     ]
    }
   ],
   "source": [
    "%env CUDA_DEVICE_ORDER=PCI_BUS_ID\n",
    "%env CUDA_VISIBLE_DEVICES=1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-11-12T22:49:49.053905Z",
     "start_time": "2020-11-12T22:49:40.670302Z"
    }
   },
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "from tfumap.semisupervised_keras import pretrained_networks\n",
    "from tfumap.semisupervised_keras import load_architecture\n",
    "from tfumap.paths import MODEL_DIR"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-11-12T22:49:49.064594Z",
     "start_time": "2020-11-12T22:49:49.056195Z"
    }
   },
   "outputs": [],
   "source": [
    "from tfumap.semisupervised_keras import load_dataset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-11-12T22:49:49.077074Z",
     "start_time": "2020-11-12T22:49:49.066786Z"
    }
   },
   "outputs": [],
   "source": [
    "dataset = \"fmnist\"\n",
    "n_latent_dims = 1024"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-11-12T22:49:57.985559Z",
     "start_time": "2020-11-12T22:49:56.729840Z"
    }
   },
   "outputs": [],
   "source": [
    "(\n",
    "    X_train,\n",
    "    X_test,\n",
    "    X_labeled,\n",
    "    Y_labeled,\n",
    "    Y_masked,\n",
    "    X_valid,\n",
    "    Y_train,\n",
    "    Y_test,\n",
    "    Y_valid,\n",
    "    Y_valid_one_hot,\n",
    "    Y_labeled_one_hot,\n",
    "    num_classes,\n",
    "    dims\n",
    ") = load_dataset(dataset, 'full')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-11-12T22:49:58.917753Z",
     "start_time": "2020-11-12T22:49:57.987296Z"
    }
   },
   "outputs": [],
   "source": [
    "encoder, classifier, embedder = load_architecture(dataset, n_latent_dims)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-11-12T22:49:58.922100Z",
     "start_time": "2020-11-12T22:49:58.919581Z"
    }
   },
   "outputs": [],
   "source": [
    "aug_types = [\n",
    "    \"not_augmented\",\n",
    "    \"augmented\",\n",
    "    \"umap_euclidean\",\n",
    "    \"umap_learned\",\n",
    "    \"umap_augmented_learned\",\n",
    "    \"umap_euclidean_augmented\",\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-11-12T22:51:57.856509Z",
     "start_time": "2020-11-12T22:50:00.856996Z"
    },
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Logging before flag parsing goes to stderr.\n",
      "W1112 14:50:00.923120 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d646390> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d646828>).\n",
      "W1112 14:50:00.926978 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d61d7f0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d66bda0>).\n",
      "W1112 14:50:01.026499 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d727470> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d70e780>).\n",
      "W1112 14:50:01.030123 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d70e780> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169da143c8>).\n",
      "W1112 14:50:01.038447 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d6eea20> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d6eecf8>).\n",
      "W1112 14:50:01.044342 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d6eecf8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d6ee6d8>).\n",
      "W1112 14:50:01.048183 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169cb0a518> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169cb0a828>).\n",
      "W1112 14:50:01.053445 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169cb0a828> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169cb0a978>).\n",
      "W1112 14:50:01.062080 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d5e3c88> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d5e62b0>).\n",
      "W1112 14:50:01.064716 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d5e62b0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d5e6518>).\n",
      "W1112 14:50:01.069164 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d8310f0> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d831320>).\n",
      "W1112 14:50:01.071709 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d831320> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d831588>).\n",
      "W1112 14:50:01.076090 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d264048> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d264358>).\n",
      "W1112 14:50:01.078691 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d264358> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d2645c0>).\n",
      "W1112 14:50:01.086303 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d9b7748> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d9b76a0>).\n",
      "W1112 14:50:01.088822 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d9b76a0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d37e048>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:50:01.092722 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d8aeb38> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d8aee10>).\n",
      "W1112 14:50:01.095576 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d8aee10> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d8b6080>).\n",
      "W1112 14:50:01.099447 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169da89b70> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169da89e48>).\n",
      "W1112 14:50:01.102744 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169da89e48> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169da990b8>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.6068 +- 0.004884606023007384\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:50:06.367157 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d646390> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d646828>).\n",
      "W1112 14:50:06.370140 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d61d7f0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d66bda0>).\n",
      "W1112 14:50:06.494351 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d727470> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d70e780>).\n",
      "W1112 14:50:06.497753 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d70e780> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169da143c8>).\n",
      "W1112 14:50:06.501918 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d6eea20> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d6eecf8>).\n",
      "W1112 14:50:06.505160 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d6eecf8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d6ee6d8>).\n",
      "W1112 14:50:06.510122 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169cb0a518> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169cb0a828>).\n",
      "W1112 14:50:06.513695 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169cb0a828> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169cb0a978>).\n",
      "W1112 14:50:06.520047 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d5e3c88> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d5e62b0>).\n",
      "W1112 14:50:06.522841 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d5e62b0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d5e6518>).\n",
      "W1112 14:50:06.526683 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d8310f0> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d831320>).\n",
      "W1112 14:50:06.529801 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d831320> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d831588>).\n",
      "W1112 14:50:06.536365 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d264048> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d264358>).\n",
      "W1112 14:50:06.539916 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d264358> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d2645c0>).\n",
      "W1112 14:50:06.545988 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d9b7748> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d9b76a0>).\n",
      "W1112 14:50:06.549619 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d9b76a0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d37e048>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:50:06.553529 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d8aeb38> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d8aee10>).\n",
      "W1112 14:50:06.556565 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d8aee10> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d8b6080>).\n",
      "W1112 14:50:06.560276 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169da89b70> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169da89e48>).\n",
      "W1112 14:50:06.563296 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169da89e48> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169da990b8>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 2ms/step\n",
      "pretrained acc: 0.692 +- 0.004616665463297075\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 2ms/step\n",
      "pretrained acc: 0.7144 +- 0.004516997232675708\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 2ms/step\n",
      "pretrained acc: 0.6286 +- 0.0048317909723000225\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 2ms/step\n",
      "pretrained acc: 0.747 +- 0.00434730951279064\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 2ms/step\n",
      "pretrained acc: 0.7373 +- 0.0044010079527308284\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:50:22.243479 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d646390> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d646828>).\n",
      "W1112 14:50:22.245498 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d61d7f0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d66bda0>).\n",
      "W1112 14:50:22.343080 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d727470> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d70e780>).\n",
      "W1112 14:50:22.346766 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d70e780> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169da143c8>).\n",
      "W1112 14:50:22.351805 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d6eea20> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d6eecf8>).\n",
      "W1112 14:50:22.354663 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d6eecf8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d6ee6d8>).\n",
      "W1112 14:50:22.358565 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169cb0a518> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169cb0a828>).\n",
      "W1112 14:50:22.361372 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169cb0a828> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169cb0a978>).\n",
      "W1112 14:50:22.367467 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d5e3c88> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d5e62b0>).\n",
      "W1112 14:50:22.370288 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d5e62b0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d5e6518>).\n",
      "W1112 14:50:22.374211 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d8310f0> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d831320>).\n",
      "W1112 14:50:22.377055 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d831320> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d831588>).\n",
      "W1112 14:50:22.381027 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d264048> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d264358>).\n",
      "W1112 14:50:22.383909 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d264358> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d2645c0>).\n",
      "W1112 14:50:22.390107 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d9b7748> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d9b76a0>).\n",
      "W1112 14:50:22.392952 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d9b76a0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d37e048>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:50:22.396921 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d8aeb38> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d8aee10>).\n",
      "W1112 14:50:22.399748 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d8aee10> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d8b6080>).\n",
      "W1112 14:50:22.403675 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169da89b70> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169da89e48>).\n",
      "W1112 14:50:22.406504 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169da89e48> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169da990b8>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 2ms/step\n",
      "pretrained acc: 0.7439 +- 0.0043647770848005505\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:50:25.174007 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d646390> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d646828>).\n",
      "W1112 14:50:25.176677 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d61d7f0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d66bda0>).\n",
      "W1112 14:50:25.310905 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d727470> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d70e780>).\n",
      "W1112 14:50:25.316444 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d70e780> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169da143c8>).\n",
      "W1112 14:50:25.320313 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d6eea20> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d6eecf8>).\n",
      "W1112 14:50:25.323030 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d6eecf8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d6ee6d8>).\n",
      "W1112 14:50:25.326810 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169cb0a518> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169cb0a828>).\n",
      "W1112 14:50:25.329509 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169cb0a828> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169cb0a978>).\n",
      "W1112 14:50:25.335439 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d5e3c88> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d5e62b0>).\n",
      "W1112 14:50:25.338144 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d5e62b0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d5e6518>).\n",
      "W1112 14:50:25.341921 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d8310f0> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d831320>).\n",
      "W1112 14:50:25.344642 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d831320> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d831588>).\n",
      "W1112 14:50:25.348452 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d264048> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d264358>).\n",
      "W1112 14:50:25.351179 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d264358> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d2645c0>).\n",
      "W1112 14:50:25.357202 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d9b7748> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d9b76a0>).\n",
      "W1112 14:50:25.359956 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d9b76a0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d37e048>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:50:25.363792 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d8aeb38> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d8aee10>).\n",
      "W1112 14:50:25.366522 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d8aee10> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d8b6080>).\n",
      "W1112 14:50:25.370427 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169da89b70> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169da89e48>).\n",
      "W1112 14:50:25.373172 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169da89e48> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169da990b8>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.7962 +- 0.004028219954272606\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.7845 +- 0.004111687609729124\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 2ms/step\n",
      "pretrained acc: 0.7425 +- 0.004372570754144522\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.8263 +- 0.0037885130328401935\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.8322 +- 0.003736885869276716\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:50:40.994340 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d646390> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d646828>).\n",
      "W1112 14:50:40.997243 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d61d7f0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d66bda0>).\n",
      "W1112 14:50:41.388543 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d727470> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d70e780>).\n",
      "W1112 14:50:41.391506 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d70e780> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169da143c8>).\n",
      "W1112 14:50:41.395550 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d6eea20> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d6eecf8>).\n",
      "W1112 14:50:41.398518 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d6eecf8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d6ee6d8>).\n",
      "W1112 14:50:41.402484 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169cb0a518> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169cb0a828>).\n",
      "W1112 14:50:41.405411 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169cb0a828> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169cb0a978>).\n",
      "W1112 14:50:41.412583 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d5e3c88> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d5e62b0>).\n",
      "W1112 14:50:41.415474 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d5e62b0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d5e6518>).\n",
      "W1112 14:50:41.419487 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d8310f0> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d831320>).\n",
      "W1112 14:50:41.422397 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d831320> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d831588>).\n",
      "W1112 14:50:41.427107 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d264048> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d264358>).\n",
      "W1112 14:50:41.430396 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d264358> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d2645c0>).\n",
      "W1112 14:50:41.437774 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d9b7748> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d9b76a0>).\n",
      "W1112 14:50:41.440582 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d9b76a0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d37e048>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:50:41.444452 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d8aeb38> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d8aee10>).\n",
      "W1112 14:50:41.447247 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d8aee10> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d8b6080>).\n",
      "W1112 14:50:41.451132 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169da89b70> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169da89e48>).\n",
      "W1112 14:50:41.453938 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169da89e48> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169da990b8>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 2ms/step\n",
      "pretrained acc: 0.8351 +- 0.003710902720363335\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:50:44.200617 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d646390> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d646828>).\n",
      "W1112 14:50:44.203094 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d61d7f0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d66bda0>).\n",
      "W1112 14:50:44.325016 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d727470> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d70e780>).\n",
      "W1112 14:50:44.328358 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d70e780> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169da143c8>).\n",
      "W1112 14:50:44.332373 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d6eea20> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d6eecf8>).\n",
      "W1112 14:50:44.335273 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d6eecf8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d6ee6d8>).\n",
      "W1112 14:50:44.339284 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169cb0a518> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169cb0a828>).\n",
      "W1112 14:50:44.342219 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169cb0a828> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169cb0a978>).\n",
      "W1112 14:50:44.348417 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d5e3c88> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d5e62b0>).\n",
      "W1112 14:50:44.351328 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d5e62b0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d5e6518>).\n",
      "W1112 14:50:44.355326 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d8310f0> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d831320>).\n",
      "W1112 14:50:44.358259 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d831320> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d831588>).\n",
      "W1112 14:50:44.367846 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d264048> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d264358>).\n",
      "W1112 14:50:44.370759 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d264358> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d2645c0>).\n",
      "W1112 14:50:44.377179 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d9b7748> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d9b76a0>).\n",
      "W1112 14:50:44.379966 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d9b76a0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d37e048>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:50:44.383841 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d8aeb38> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d8aee10>).\n",
      "W1112 14:50:44.386626 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d8aee10> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d8b6080>).\n",
      "W1112 14:50:44.390468 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169da89b70> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169da89e48>).\n",
      "W1112 14:50:44.393265 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169da89e48> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169da990b8>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.8598 +- 0.003471944123974348\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 2ms/step\n",
      "pretrained acc: 0.841 +- 0.0036567608617463633\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.8352 +- 0.0037099994609164025\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.8797 +- 0.0032531201945209458\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.864 +- 0.0034278856457005675\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:50:59.693650 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d646390> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d646828>).\n",
      "W1112 14:50:59.696290 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d61d7f0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d66bda0>).\n",
      "W1112 14:50:59.802440 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d727470> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d70e780>).\n",
      "W1112 14:50:59.805737 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d70e780> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169da143c8>).\n",
      "W1112 14:50:59.809867 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d6eea20> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d6eecf8>).\n",
      "W1112 14:50:59.813171 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d6eecf8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d6ee6d8>).\n",
      "W1112 14:50:59.818397 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169cb0a518> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169cb0a828>).\n",
      "W1112 14:50:59.822195 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169cb0a828> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169cb0a978>).\n",
      "W1112 14:50:59.829680 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d5e3c88> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d5e62b0>).\n",
      "W1112 14:50:59.832707 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d5e62b0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d5e6518>).\n",
      "W1112 14:50:59.837911 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d8310f0> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d831320>).\n",
      "W1112 14:50:59.841345 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d831320> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d831588>).\n",
      "W1112 14:50:59.845333 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d264048> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d264358>).\n",
      "W1112 14:50:59.848309 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d264358> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d2645c0>).\n",
      "W1112 14:50:59.854484 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d9b7748> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d9b76a0>).\n",
      "W1112 14:50:59.857598 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d9b76a0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d37e048>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:50:59.861680 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d8aeb38> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d8aee10>).\n",
      "W1112 14:50:59.864702 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d8aee10> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d8b6080>).\n",
      "W1112 14:50:59.868745 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169da89b70> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169da89e48>).\n",
      "W1112 14:50:59.871694 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169da89e48> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169da990b8>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.889 +- 0.0031413213780191298\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:51:02.795118 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d646390> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d646828>).\n",
      "W1112 14:51:02.798077 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d61d7f0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d66bda0>).\n",
      "W1112 14:51:03.093965 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d727470> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d70e780>).\n",
      "W1112 14:51:03.097739 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d70e780> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169da143c8>).\n",
      "W1112 14:51:03.101838 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d6eea20> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d6eecf8>).\n",
      "W1112 14:51:03.105495 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d6eecf8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d6ee6d8>).\n",
      "W1112 14:51:03.111192 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169cb0a518> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169cb0a828>).\n",
      "W1112 14:51:03.114708 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169cb0a828> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169cb0a978>).\n",
      "W1112 14:51:03.121320 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d5e3c88> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d5e62b0>).\n",
      "W1112 14:51:03.124013 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d5e62b0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d5e6518>).\n",
      "W1112 14:51:03.127882 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d8310f0> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d831320>).\n",
      "W1112 14:51:03.130812 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d831320> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d831588>).\n",
      "W1112 14:51:03.134910 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d264048> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d264358>).\n",
      "W1112 14:51:03.140736 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d264358> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d2645c0>).\n",
      "W1112 14:51:03.149717 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d9b7748> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d9b76a0>).\n",
      "W1112 14:51:03.153335 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d9b76a0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d37e048>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:51:03.157607 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d8aeb38> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d8aee10>).\n",
      "W1112 14:51:03.160898 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d8aee10> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d8b6080>).\n",
      "W1112 14:51:03.166155 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169da89b70> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169da89e48>).\n",
      "W1112 14:51:03.169762 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169da89e48> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169da990b8>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.9009 +- 0.0029879623491603775\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.8846 +- 0.0031950405318242835\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 2ms/step\n",
      "pretrained acc: 0.8887 +- 0.0031450327502269347\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 2ms/step\n",
      "pretrained acc: 0.9081 +- 0.002888847347991929\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 2ms/step\n",
      "pretrained acc: 0.9003 +- 0.0029959958277674553\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:51:18.529945 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d646390> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d646828>).\n",
      "W1112 14:51:18.532041 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d61d7f0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d66bda0>).\n",
      "W1112 14:51:18.641589 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d727470> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d70e780>).\n",
      "W1112 14:51:18.646222 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d70e780> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169da143c8>).\n",
      "W1112 14:51:18.652329 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d6eea20> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d6eecf8>).\n",
      "W1112 14:51:18.656001 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d6eecf8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d6ee6d8>).\n",
      "W1112 14:51:18.663187 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169cb0a518> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169cb0a828>).\n",
      "W1112 14:51:18.666463 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169cb0a828> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169cb0a978>).\n",
      "W1112 14:51:18.674617 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d5e3c88> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d5e62b0>).\n",
      "W1112 14:51:18.678548 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d5e62b0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d5e6518>).\n",
      "W1112 14:51:18.684193 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d8310f0> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d831320>).\n",
      "W1112 14:51:18.687220 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d831320> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d831588>).\n",
      "W1112 14:51:18.693174 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d264048> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d264358>).\n",
      "W1112 14:51:18.696345 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d264358> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d2645c0>).\n",
      "W1112 14:51:18.702701 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d9b7748> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d9b76a0>).\n",
      "W1112 14:51:18.705785 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d9b76a0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d37e048>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:51:18.709776 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d8aeb38> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d8aee10>).\n",
      "W1112 14:51:18.713143 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d8aee10> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d8b6080>).\n",
      "W1112 14:51:18.717564 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169da89b70> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169da89e48>).\n",
      "W1112 14:51:18.720526 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169da89e48> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169da990b8>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.9205 +- 0.002705175595039997\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:51:21.451332 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d646390> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d646828>).\n",
      "W1112 14:51:21.453419 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d61d7f0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d66bda0>).\n",
      "W1112 14:51:21.556342 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d727470> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d70e780>).\n",
      "W1112 14:51:21.559455 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d70e780> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169da143c8>).\n",
      "W1112 14:51:21.563576 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d6eea20> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d6eecf8>).\n",
      "W1112 14:51:21.566391 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d6eecf8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d6ee6d8>).\n",
      "W1112 14:51:21.570295 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169cb0a518> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169cb0a828>).\n",
      "W1112 14:51:21.573021 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169cb0a828> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169cb0a978>).\n",
      "W1112 14:51:21.579907 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d5e3c88> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d5e62b0>).\n",
      "W1112 14:51:21.582617 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d5e62b0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d5e6518>).\n",
      "W1112 14:51:21.586767 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d8310f0> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d831320>).\n",
      "W1112 14:51:21.590395 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d831320> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d831588>).\n",
      "W1112 14:51:21.595475 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d264048> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d264358>).\n",
      "W1112 14:51:21.599065 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d264358> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d2645c0>).\n",
      "W1112 14:51:21.606080 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d9b7748> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d9b76a0>).\n",
      "W1112 14:51:21.608935 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d9b76a0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d37e048>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:51:21.612797 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d8aeb38> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d8aee10>).\n",
      "W1112 14:51:21.615644 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d8aee10> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d8b6080>).\n",
      "W1112 14:51:21.619521 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169da89b70> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169da89e48>).\n",
      "W1112 14:51:21.622271 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169da89e48> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169da990b8>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.9322 +- 0.0025140238662351637\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.9165 +- 0.0027663649433868993\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.9196 +- 0.0027191145617645462\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 2ms/step\n",
      "pretrained acc: 0.9318 +- 0.002520887938802517\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.9299 +- 0.002553154715249352\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:51:37.696222 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d646390> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d646828>).\n",
      "W1112 14:51:37.699132 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d61d7f0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d66bda0>).\n",
      "W1112 14:51:37.986895 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d727470> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d70e780>).\n",
      "W1112 14:51:37.990277 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d70e780> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169da143c8>).\n",
      "W1112 14:51:37.994260 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d6eea20> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d6eecf8>).\n",
      "W1112 14:51:37.997339 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d6eecf8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d6ee6d8>).\n",
      "W1112 14:51:38.001468 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169cb0a518> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169cb0a828>).\n",
      "W1112 14:51:38.004345 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169cb0a828> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169cb0a978>).\n",
      "W1112 14:51:38.010407 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d5e3c88> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d5e62b0>).\n",
      "W1112 14:51:38.013241 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d5e62b0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d5e6518>).\n",
      "W1112 14:51:38.017310 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d8310f0> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d831320>).\n",
      "W1112 14:51:38.020066 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d831320> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d831588>).\n",
      "W1112 14:51:38.023894 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d264048> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d264358>).\n",
      "W1112 14:51:38.026976 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d264358> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d2645c0>).\n",
      "W1112 14:51:38.033176 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d9b7748> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d9b76a0>).\n",
      "W1112 14:51:38.037562 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d9b76a0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d37e048>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:51:38.041339 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d8aeb38> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d8aee10>).\n",
      "W1112 14:51:38.045333 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d8aee10> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d8b6080>).\n",
      "W1112 14:51:38.050541 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169da89b70> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169da89e48>).\n",
      "W1112 14:51:38.053475 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169da89e48> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169da990b8>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.9427 +- 0.002324149521868161\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:51:41.083451 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d646390> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d646828>).\n",
      "W1112 14:51:41.086169 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d61d7f0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d66bda0>).\n",
      "W1112 14:51:41.238535 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d727470> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d70e780>).\n",
      "W1112 14:51:41.241492 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d70e780> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169da143c8>).\n",
      "W1112 14:51:41.245244 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d6eea20> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d6eecf8>).\n",
      "W1112 14:51:41.248130 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d6eecf8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d6ee6d8>).\n",
      "W1112 14:51:41.252032 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169cb0a518> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169cb0a828>).\n",
      "W1112 14:51:41.254873 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169cb0a828> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169cb0a978>).\n",
      "W1112 14:51:41.260926 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d5e3c88> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d5e62b0>).\n",
      "W1112 14:51:41.263734 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d5e62b0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d5e6518>).\n",
      "W1112 14:51:41.267578 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d8310f0> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d831320>).\n",
      "W1112 14:51:41.270381 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d831320> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d831588>).\n",
      "W1112 14:51:41.274285 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d264048> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d264358>).\n",
      "W1112 14:51:41.277090 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d264358> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d2645c0>).\n",
      "W1112 14:51:41.285047 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d9b7748> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d9b76a0>).\n",
      "W1112 14:51:41.287845 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d9b76a0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d37e048>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:51:41.292553 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169d8aeb38> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d8aee10>).\n",
      "W1112 14:51:41.296051 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169d8aee10> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169d8b6080>).\n",
      "W1112 14:51:41.300869 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7f169da89b70> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169da89e48>).\n",
      "W1112 14:51:41.303779 139738279618368 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7f169da89e48> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7f169da990b8>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.9488 +- 0.0022040544457884877\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.9466 +- 0.0022482980229498045\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.9443 +- 0.0022934147030138265\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.9525 +- 0.0021270578271405786\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 1s 2ms/step\n",
      "pretrained acc: 0.9521 +- 0.002135546534262365\n"
     ]
    }
   ],
   "source": [
    "for labels_per_class in [4, 16, 64, 256, 1024, 'full']:\n",
    "    for aug_str in aug_types:\n",
    "        pretrained_weights_loc = pretrained_networks[dataset][aug_str][labels_per_class]\n",
    "        load_folder = (\n",
    "            MODEL_DIR\n",
    "            / \"semisupervised-keras\"\n",
    "            / dataset\n",
    "            / str(labels_per_class)\n",
    "            / pretrained_weights_loc\n",
    "        )\n",
    "        classifier.load_weights((load_folder / \"classifier\").as_posix())\n",
    "        encoder.load_weights((load_folder / \"encoder\").as_posix())\n",
    "        # test current acc\n",
    "        pretrained_predictions = classifier.predict(encoder.predict(X_test, verbose=True), verbose=True)\n",
    "        pretrained_predictions = np.argmax(pretrained_predictions, axis=1)\n",
    "        pretrained_acc = pretrained_predictions == Y_test\n",
    "        mean_acc = np.mean(pretrained_acc)\n",
    "        sem_acc = np.std(pretrained_acc) / np.sqrt(len(pretrained_acc))\n",
    "        np.save(load_folder / 'test_loss_SEM.npy', (mean_acc, sem_acc))\n",
    "        print('pretrained acc: {} +- {}'.format(mean_acc, sem_acc))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
