{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-11-12T22:35:50.095446Z",
     "start_time": "2020-11-12T22:35:50.090087Z"
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "env: CUDA_DEVICE_ORDER=PCI_BUS_ID\n",
      "env: CUDA_VISIBLE_DEVICES=1\n"
     ]
    }
   ],
   "source": [
    "%env CUDA_DEVICE_ORDER=PCI_BUS_ID\n",
    "%env CUDA_VISIBLE_DEVICES=1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-11-12T22:35:58.715844Z",
     "start_time": "2020-11-12T22:35:50.243857Z"
    }
   },
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "from tfumap.semisupervised_keras import pretrained_networks\n",
    "from tfumap.semisupervised_keras import load_architecture\n",
    "from tfumap.paths import MODEL_DIR"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-11-12T22:35:58.723837Z",
     "start_time": "2020-11-12T22:35:58.717443Z"
    }
   },
   "outputs": [],
   "source": [
    "from tfumap.semisupervised_keras import load_dataset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-11-12T22:35:58.734208Z",
     "start_time": "2020-11-12T22:35:58.725150Z"
    }
   },
   "outputs": [],
   "source": [
    "dataset = \"cifar10\"\n",
    "n_latent_dims = 1024"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-11-12T22:36:00.333484Z",
     "start_time": "2020-11-12T22:35:58.735506Z"
    }
   },
   "outputs": [],
   "source": [
    "(\n",
    "    X_train,\n",
    "    X_test,\n",
    "    X_labeled,\n",
    "    Y_labeled,\n",
    "    Y_masked,\n",
    "    X_valid,\n",
    "    Y_train,\n",
    "    Y_test,\n",
    "    Y_valid,\n",
    "    Y_valid_one_hot,\n",
    "    Y_labeled_one_hot,\n",
    "    num_classes,\n",
    "    dims\n",
    ") = load_dataset(dataset, 'full')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-11-12T22:36:01.241862Z",
     "start_time": "2020-11-12T22:36:00.334839Z"
    }
   },
   "outputs": [],
   "source": [
    "encoder, classifier, embedder = load_architecture(dataset, n_latent_dims)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-11-12T22:36:01.245497Z",
     "start_time": "2020-11-12T22:36:01.243174Z"
    }
   },
   "outputs": [],
   "source": [
    "aug_types = [\n",
    "    \"not_augmented\",\n",
    "    \"augmented\",\n",
    "    \"umap_euclidean\",\n",
    "    \"umap_learned\",\n",
    "    \"umap_augmented_learned\",\n",
    "    \"umap_euclidean_augmented\",\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-11-12T22:38:18.648827Z",
     "start_time": "2020-11-12T22:36:14.622432Z"
    },
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Logging before flag parsing goes to stderr.\n",
      "W1112 14:36:14.715609 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5415f400> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5415f898>).\n",
      "W1112 14:36:14.717746 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd54152860> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5440de10>).\n",
      "W1112 14:36:14.815083 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4b8ae748> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546ec4e0>).\n",
      "W1112 14:36:14.818117 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546ec4e0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd541ffc88>).\n",
      "W1112 14:36:14.821880 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd546d8518> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546d8080>).\n",
      "W1112 14:36:14.824577 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546d8080> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546d8978>).\n",
      "W1112 14:36:14.828322 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5449f588> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5449f898>).\n",
      "W1112 14:36:14.831006 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5449f898> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5449f9e8>).\n",
      "W1112 14:36:14.836917 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4b991cf8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4b98f320>).\n",
      "W1112 14:36:14.839612 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4b98f320> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd4b98f588>).\n",
      "W1112 14:36:14.843354 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd544fa160> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd544fa390>).\n",
      "W1112 14:36:14.846023 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd544fa390> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd544fa5f8>).\n",
      "W1112 14:36:14.849749 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4c1fa0b8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4c1fa3c8>).\n",
      "W1112 14:36:14.852434 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4c1fa3c8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd4c1fa630>).\n",
      "W1112 14:36:14.858322 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5411a7b8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5411acf8>).\n",
      "W1112 14:36:14.861004 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5411acf8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546a50b8>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:36:14.864732 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5464aba8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5464ae80>).\n",
      "W1112 14:36:14.867413 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5464ae80> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546510f0>).\n",
      "W1112 14:36:14.871127 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5477ebe0> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5477eeb8>).\n",
      "W1112 14:36:14.873806 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5477eeb8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd54742128>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.217 +- 0.004122026200790092\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:36:20.299094 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5415f400> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5415f898>).\n",
      "W1112 14:36:20.301682 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd54152860> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5440de10>).\n",
      "W1112 14:36:20.432650 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4b8ae748> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546ec4e0>).\n",
      "W1112 14:36:20.436034 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546ec4e0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd541ffc88>).\n",
      "W1112 14:36:20.439958 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd546d8518> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546d8080>).\n",
      "W1112 14:36:20.442793 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546d8080> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546d8978>).\n",
      "W1112 14:36:20.446729 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5449f588> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5449f898>).\n",
      "W1112 14:36:20.449638 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5449f898> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5449f9e8>).\n",
      "W1112 14:36:20.455682 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4b991cf8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4b98f320>).\n",
      "W1112 14:36:20.458553 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4b98f320> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd4b98f588>).\n",
      "W1112 14:36:20.462465 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd544fa160> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd544fa390>).\n",
      "W1112 14:36:20.469417 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd544fa390> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd544fa5f8>).\n",
      "W1112 14:36:20.474421 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4c1fa0b8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4c1fa3c8>).\n",
      "W1112 14:36:20.477052 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4c1fa3c8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd4c1fa630>).\n",
      "W1112 14:36:20.483084 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5411a7b8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5411acf8>).\n",
      "W1112 14:36:20.485859 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5411acf8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546a50b8>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:36:20.489761 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5464aba8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5464ae80>).\n",
      "W1112 14:36:20.492538 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5464ae80> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546510f0>).\n",
      "W1112 14:36:20.496365 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5477ebe0> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5477eeb8>).\n",
      "W1112 14:36:20.499145 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5477eeb8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd54742128>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.2814 +- 0.004496821544157606\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.1895 +- 0.003919052819240894\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.1988 +- 0.003990971811476498\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.3509 +- 0.004772517050781485\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.2427 +- 0.004287151851754262\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:36:37.290539 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5415f400> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5415f898>).\n",
      "W1112 14:36:37.292938 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd54152860> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5440de10>).\n",
      "W1112 14:36:37.411410 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4b8ae748> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546ec4e0>).\n",
      "W1112 14:36:37.414447 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546ec4e0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd541ffc88>).\n",
      "W1112 14:36:37.418388 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd546d8518> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546d8080>).\n",
      "W1112 14:36:37.421237 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546d8080> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546d8978>).\n",
      "W1112 14:36:37.425700 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5449f588> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5449f898>).\n",
      "W1112 14:36:37.428585 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5449f898> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5449f9e8>).\n",
      "W1112 14:36:37.435862 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4b991cf8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4b98f320>).\n",
      "W1112 14:36:37.439634 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4b98f320> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd4b98f588>).\n",
      "W1112 14:36:37.443478 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd544fa160> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd544fa390>).\n",
      "W1112 14:36:37.446266 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd544fa390> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd544fa5f8>).\n",
      "W1112 14:36:37.450068 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4c1fa0b8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4c1fa3c8>).\n",
      "W1112 14:36:37.452860 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4c1fa3c8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd4c1fa630>).\n",
      "W1112 14:36:37.459645 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5411a7b8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5411acf8>).\n",
      "W1112 14:36:37.462396 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5411acf8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546a50b8>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:36:37.466290 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5464aba8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5464ae80>).\n",
      "W1112 14:36:37.469545 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5464ae80> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546510f0>).\n",
      "W1112 14:36:37.474414 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5477ebe0> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5477eeb8>).\n",
      "W1112 14:36:37.477338 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5477eeb8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd54742128>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 2ms/step\n",
      "pretrained acc: 0.3019 +- 0.004590821168375\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:36:40.675624 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5415f400> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5415f898>).\n",
      "W1112 14:36:40.677464 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd54152860> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5440de10>).\n",
      "W1112 14:36:40.776970 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4b8ae748> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546ec4e0>).\n",
      "W1112 14:36:40.779935 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546ec4e0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd541ffc88>).\n",
      "W1112 14:36:40.783957 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd546d8518> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546d8080>).\n",
      "W1112 14:36:40.786887 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546d8080> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546d8978>).\n",
      "W1112 14:36:40.790852 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5449f588> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5449f898>).\n",
      "W1112 14:36:40.793800 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5449f898> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5449f9e8>).\n",
      "W1112 14:36:40.801065 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4b991cf8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4b98f320>).\n",
      "W1112 14:36:40.804009 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4b98f320> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd4b98f588>).\n",
      "W1112 14:36:40.809138 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd544fa160> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd544fa390>).\n",
      "W1112 14:36:40.812631 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd544fa390> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd544fa5f8>).\n",
      "W1112 14:36:40.816613 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4c1fa0b8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4c1fa3c8>).\n",
      "W1112 14:36:40.819526 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4c1fa3c8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd4c1fa630>).\n",
      "W1112 14:36:40.825682 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5411a7b8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5411acf8>).\n",
      "W1112 14:36:40.828595 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5411acf8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546a50b8>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:36:40.832496 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5464aba8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5464ae80>).\n",
      "W1112 14:36:40.835289 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5464ae80> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546510f0>).\n",
      "W1112 14:36:40.839181 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5477ebe0> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5477eeb8>).\n",
      "W1112 14:36:40.842024 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5477eeb8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd54742128>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 2ms/step\n",
      "pretrained acc: 0.4042 +- 0.004907365484656712\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 2ms/step\n",
      "pretrained acc: 0.2867 +- 0.004522202007871829\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.306 +- 0.004608296865437383\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.5035 +- 0.004999877498499338\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.3794 +- 0.0048523771493980145\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:36:57.524598 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5415f400> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5415f898>).\n",
      "W1112 14:36:57.527039 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd54152860> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5440de10>).\n",
      "W1112 14:36:57.635918 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4b8ae748> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546ec4e0>).\n",
      "W1112 14:36:57.638891 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546ec4e0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd541ffc88>).\n",
      "W1112 14:36:57.642508 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd546d8518> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546d8080>).\n",
      "W1112 14:36:57.645033 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546d8080> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546d8978>).\n",
      "W1112 14:36:57.648663 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5449f588> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5449f898>).\n",
      "W1112 14:36:57.651144 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5449f898> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5449f9e8>).\n",
      "W1112 14:36:57.660580 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4b991cf8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4b98f320>).\n",
      "W1112 14:36:57.663968 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4b98f320> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd4b98f588>).\n",
      "W1112 14:36:57.667736 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd544fa160> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd544fa390>).\n",
      "W1112 14:36:57.670311 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd544fa390> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd544fa5f8>).\n",
      "W1112 14:36:57.673885 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4c1fa0b8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4c1fa3c8>).\n",
      "W1112 14:36:57.676428 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4c1fa3c8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd4c1fa630>).\n",
      "W1112 14:36:57.682140 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5411a7b8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5411acf8>).\n",
      "W1112 14:36:57.684767 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5411acf8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546a50b8>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:36:57.688336 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5464aba8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5464ae80>).\n",
      "W1112 14:36:57.690854 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5464ae80> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546510f0>).\n",
      "W1112 14:36:57.694397 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5477ebe0> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5477eeb8>).\n",
      "W1112 14:36:57.696938 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5477eeb8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd54742128>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.4992 +- 0.004999993599995904\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:37:00.654217 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5415f400> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5415f898>).\n",
      "W1112 14:37:00.657096 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd54152860> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5440de10>).\n",
      "W1112 14:37:00.755254 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4b8ae748> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546ec4e0>).\n",
      "W1112 14:37:00.758072 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546ec4e0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd541ffc88>).\n",
      "W1112 14:37:00.762091 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd546d8518> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546d8080>).\n",
      "W1112 14:37:00.765135 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546d8080> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546d8978>).\n",
      "W1112 14:37:00.769213 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5449f588> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5449f898>).\n",
      "W1112 14:37:00.772304 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5449f898> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5449f9e8>).\n",
      "W1112 14:37:00.780678 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4b991cf8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4b98f320>).\n",
      "W1112 14:37:00.783563 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4b98f320> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd4b98f588>).\n",
      "W1112 14:37:00.787623 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd544fa160> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd544fa390>).\n",
      "W1112 14:37:00.790671 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd544fa390> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd544fa5f8>).\n",
      "W1112 14:37:00.794676 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4c1fa0b8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4c1fa3c8>).\n",
      "W1112 14:37:00.797368 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4c1fa3c8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd4c1fa630>).\n",
      "W1112 14:37:00.803917 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5411a7b8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5411acf8>).\n",
      "W1112 14:37:00.806483 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5411acf8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546a50b8>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:37:00.810228 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5464aba8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5464ae80>).\n",
      "W1112 14:37:00.813826 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5464ae80> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546510f0>).\n",
      "W1112 14:37:00.817636 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5477ebe0> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5477eeb8>).\n",
      "W1112 14:37:00.821350 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5477eeb8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd54742128>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.5993 +- 0.0049004031466808925\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.4503 +- 0.004975237783262224\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.5148 +- 0.004997809120004484\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.6742 +- 0.00468672977672065\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.5596 +- 0.004964351317141041\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:37:18.018986 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5415f400> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5415f898>).\n",
      "W1112 14:37:18.021568 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd54152860> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5440de10>).\n",
      "W1112 14:37:18.134469 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4b8ae748> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546ec4e0>).\n",
      "W1112 14:37:18.137956 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546ec4e0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd541ffc88>).\n",
      "W1112 14:37:18.142807 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd546d8518> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546d8080>).\n",
      "W1112 14:37:18.145533 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546d8080> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546d8978>).\n",
      "W1112 14:37:18.149244 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5449f588> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5449f898>).\n",
      "W1112 14:37:18.151952 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5449f898> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5449f9e8>).\n",
      "W1112 14:37:18.157813 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4b991cf8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4b98f320>).\n",
      "W1112 14:37:18.160480 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4b98f320> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd4b98f588>).\n",
      "W1112 14:37:18.164198 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd544fa160> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd544fa390>).\n",
      "W1112 14:37:18.166841 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd544fa390> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd544fa5f8>).\n",
      "W1112 14:37:18.170561 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4c1fa0b8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4c1fa3c8>).\n",
      "W1112 14:37:18.173243 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4c1fa3c8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd4c1fa630>).\n",
      "W1112 14:37:18.179162 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5411a7b8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5411acf8>).\n",
      "W1112 14:37:18.181896 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5411acf8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546a50b8>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:37:18.185667 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5464aba8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5464ae80>).\n",
      "W1112 14:37:18.188405 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5464ae80> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546510f0>).\n",
      "W1112 14:37:18.192176 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5477ebe0> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5477eeb8>).\n",
      "W1112 14:37:18.194859 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5477eeb8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd54742128>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.722 +- 0.004480133926569607\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:37:21.106972 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5415f400> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5415f898>).\n",
      "W1112 14:37:21.109240 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd54152860> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5440de10>).\n",
      "W1112 14:37:21.207611 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4b8ae748> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546ec4e0>).\n",
      "W1112 14:37:21.211131 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546ec4e0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd541ffc88>).\n",
      "W1112 14:37:21.216058 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd546d8518> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546d8080>).\n",
      "W1112 14:37:21.218811 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546d8080> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546d8978>).\n",
      "W1112 14:37:21.222550 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5449f588> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5449f898>).\n",
      "W1112 14:37:21.225231 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5449f898> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5449f9e8>).\n",
      "W1112 14:37:21.231165 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4b991cf8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4b98f320>).\n",
      "W1112 14:37:21.234317 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4b98f320> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd4b98f588>).\n",
      "W1112 14:37:21.238056 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd544fa160> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd544fa390>).\n",
      "W1112 14:37:21.240747 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd544fa390> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd544fa5f8>).\n",
      "W1112 14:37:21.244507 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4c1fa0b8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4c1fa3c8>).\n",
      "W1112 14:37:21.247177 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4c1fa3c8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd4c1fa630>).\n",
      "W1112 14:37:21.253112 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5411a7b8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5411acf8>).\n",
      "W1112 14:37:21.257334 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5411acf8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546a50b8>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:37:21.261093 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5464aba8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5464ae80>).\n",
      "W1112 14:37:21.264525 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5464ae80> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546510f0>).\n",
      "W1112 14:37:21.269376 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5477ebe0> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5477eeb8>).\n",
      "W1112 14:37:21.272237 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5477eeb8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd54742128>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.7664 +- 0.004231205974660181\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.6737 +- 0.004688585181054089\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.7475 +- 0.004344464869233034\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 2ms/step\n",
      "pretrained acc: 0.8205 +- 0.0038377043919509994\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.7476 +- 0.004343895026355954\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:37:38.231695 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5415f400> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5415f898>).\n",
      "W1112 14:37:38.233860 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd54152860> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5440de10>).\n",
      "W1112 14:37:38.335419 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4b8ae748> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546ec4e0>).\n",
      "W1112 14:37:38.338423 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546ec4e0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd541ffc88>).\n",
      "W1112 14:37:38.342287 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd546d8518> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546d8080>).\n",
      "W1112 14:37:38.345025 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546d8080> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546d8978>).\n",
      "W1112 14:37:38.348868 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5449f588> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5449f898>).\n",
      "W1112 14:37:38.352338 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5449f898> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5449f9e8>).\n",
      "W1112 14:37:38.358627 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4b991cf8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4b98f320>).\n",
      "W1112 14:37:38.361396 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4b98f320> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd4b98f588>).\n",
      "W1112 14:37:38.365292 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd544fa160> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd544fa390>).\n",
      "W1112 14:37:38.368067 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd544fa390> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd544fa5f8>).\n",
      "W1112 14:37:38.371954 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4c1fa0b8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4c1fa3c8>).\n",
      "W1112 14:37:38.374719 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4c1fa3c8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd4c1fa630>).\n",
      "W1112 14:37:38.381776 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5411a7b8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5411acf8>).\n",
      "W1112 14:37:38.384582 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5411acf8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546a50b8>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:37:38.388520 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5464aba8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5464ae80>).\n",
      "W1112 14:37:38.391356 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5464ae80> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546510f0>).\n",
      "W1112 14:37:38.395262 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5477ebe0> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5477eeb8>).\n",
      "W1112 14:37:38.398086 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5477eeb8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd54742128>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.838 +- 0.00368450810828257\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:37:42.062608 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5415f400> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5415f898>).\n",
      "W1112 14:37:42.064991 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd54152860> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5440de10>).\n",
      "W1112 14:37:42.308919 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4b8ae748> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546ec4e0>).\n",
      "W1112 14:37:42.312600 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546ec4e0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd541ffc88>).\n",
      "W1112 14:37:42.317693 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd546d8518> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546d8080>).\n",
      "W1112 14:37:42.320658 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546d8080> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546d8978>).\n",
      "W1112 14:37:42.324630 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5449f588> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5449f898>).\n",
      "W1112 14:37:42.327513 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5449f898> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5449f9e8>).\n",
      "W1112 14:37:42.333627 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4b991cf8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4b98f320>).\n",
      "W1112 14:37:42.336522 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4b98f320> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd4b98f588>).\n",
      "W1112 14:37:42.340494 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd544fa160> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd544fa390>).\n",
      "W1112 14:37:42.343381 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd544fa390> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd544fa5f8>).\n",
      "W1112 14:37:42.347348 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4c1fa0b8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4c1fa3c8>).\n",
      "W1112 14:37:42.350257 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4c1fa3c8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd4c1fa630>).\n",
      "W1112 14:37:42.356448 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5411a7b8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5411acf8>).\n",
      "W1112 14:37:42.359325 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5411acf8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546a50b8>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:37:42.363297 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5464aba8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5464ae80>).\n",
      "W1112 14:37:42.366209 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5464ae80> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546510f0>).\n",
      "W1112 14:37:42.370069 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5477ebe0> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5477eeb8>).\n",
      "W1112 14:37:42.372850 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5477eeb8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd54742128>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.8667 +- 0.00339898676078622\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.8289 +- 0.0037659632233998253\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.8505 +- 0.003565806360418356\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.8907 +- 0.003120152400124071\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.8524 +- 0.0035470303071724668\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:37:57.857174 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5415f400> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5415f898>).\n",
      "W1112 14:37:57.859401 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd54152860> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5440de10>).\n",
      "W1112 14:37:58.068259 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4b8ae748> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546ec4e0>).\n",
      "W1112 14:37:58.071145 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546ec4e0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd541ffc88>).\n",
      "W1112 14:37:58.075124 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd546d8518> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546d8080>).\n",
      "W1112 14:37:58.078019 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546d8080> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546d8978>).\n",
      "W1112 14:37:58.082003 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5449f588> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5449f898>).\n",
      "W1112 14:37:58.084892 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5449f898> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5449f9e8>).\n",
      "W1112 14:37:58.092180 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4b991cf8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4b98f320>).\n",
      "W1112 14:37:58.095076 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4b98f320> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd4b98f588>).\n",
      "W1112 14:37:58.099066 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd544fa160> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd544fa390>).\n",
      "W1112 14:37:58.102000 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd544fa390> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd544fa5f8>).\n",
      "W1112 14:37:58.106032 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4c1fa0b8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4c1fa3c8>).\n",
      "W1112 14:37:58.108874 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4c1fa3c8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd4c1fa630>).\n",
      "W1112 14:37:58.115992 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5411a7b8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5411acf8>).\n",
      "W1112 14:37:58.118945 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5411acf8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546a50b8>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:37:58.122848 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5464aba8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5464ae80>).\n",
      "W1112 14:37:58.125675 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5464ae80> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546510f0>).\n",
      "W1112 14:37:58.129592 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5477ebe0> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5477eeb8>).\n",
      "W1112 14:37:58.132437 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5477eeb8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd54742128>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.9049 +- 0.002933530125974506\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:38:01.763670 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5415f400> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5415f898>).\n",
      "W1112 14:38:01.766200 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd54152860> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5440de10>).\n",
      "W1112 14:38:01.881853 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4b8ae748> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546ec4e0>).\n",
      "W1112 14:38:01.885491 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546ec4e0> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd541ffc88>).\n",
      "W1112 14:38:01.890556 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd546d8518> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546d8080>).\n",
      "W1112 14:38:01.893530 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd546d8080> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546d8978>).\n",
      "W1112 14:38:01.897507 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5449f588> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5449f898>).\n",
      "W1112 14:38:01.900375 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5449f898> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd5449f9e8>).\n",
      "W1112 14:38:01.906340 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4b991cf8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4b98f320>).\n",
      "W1112 14:38:01.909104 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4b98f320> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd4b98f588>).\n",
      "W1112 14:38:01.912982 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd544fa160> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd544fa390>).\n",
      "W1112 14:38:01.915766 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd544fa390> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd544fa5f8>).\n",
      "W1112 14:38:01.919612 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd4c1fa0b8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4c1fa3c8>).\n",
      "W1112 14:38:01.922420 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd4c1fa3c8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd4c1fa630>).\n",
      "W1112 14:38:01.928753 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5411a7b8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5411acf8>).\n",
      "W1112 14:38:01.934270 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5411acf8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546a50b8>).\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "W1112 14:38:01.943220 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5464aba8> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5464ae80>).\n",
      "W1112 14:38:01.947823 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5464ae80> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd546510f0>).\n",
      "W1112 14:38:01.953031 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow_addons.layers.wrappers.WeightNormalization object at 0x7fbd5477ebe0> and <tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5477eeb8>).\n",
      "W1112 14:38:01.956897 140454179960640 base.py:272] Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x7fbd5477eeb8> and <tensorflow.python.keras.layers.advanced_activations.LeakyReLU object at 0x7fbd54742128>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.9332 +- 0.0024967530915170604\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.9129 +- 0.0028198154194911417\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.9118 +- 0.0028358554264983253\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.9324 +- 0.0025105824025512483\n",
      "313/313 [==============================] - 2s 6ms/step\n",
      "313/313 [==============================] - 0s 1ms/step\n",
      "pretrained acc: 0.9319 +- 0.0025191742694779967\n"
     ]
    }
   ],
   "source": [
    "for labels_per_class in [4, 16, 64, 256, 1024, 'full']:\n",
    "    for aug_str in aug_types:\n",
    "        pretrained_weights_loc = pretrained_networks[dataset][aug_str][labels_per_class]\n",
    "        load_folder = (\n",
    "            MODEL_DIR\n",
    "            / \"semisupervised-keras\"\n",
    "            / dataset\n",
    "            / str(labels_per_class)\n",
    "            / pretrained_weights_loc\n",
    "        )\n",
    "        classifier.load_weights((load_folder / \"classifier\").as_posix())\n",
    "        encoder.load_weights((load_folder / \"encoder\").as_posix())\n",
    "        # test current acc\n",
    "        pretrained_predictions = classifier.predict(encoder.predict(X_test, verbose=True), verbose=True)\n",
    "        pretrained_predictions = np.argmax(pretrained_predictions, axis=1)\n",
    "        pretrained_acc = pretrained_predictions == Y_test\n",
    "        mean_acc = np.mean(pretrained_acc)\n",
    "        sem_acc = np.std(pretrained_acc) / np.sqrt(len(pretrained_acc))\n",
    "        np.save(load_folder / 'test_loss_SEM.npy', (mean_acc, sem_acc))\n",
    "        print('pretrained acc: {} +- {}'.format(mean_acc, sem_acc))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
